### ISSUE TITLE
When checked options on trash can't always drag and drop files from column

### ISSUE THREAD

**Issue by Ra-V2** [HaikuArchives/8Dock#7]
This might be related to #6 
After right click on trash and check one of options drag and drop function not always work.

**Comment by humdingerb** [comment]
FWIW, I'm not able to reproduce this so far...

**Comment by Ra-V2** [comment]
Okey so now I see this generally happens to the first row. To reproduce that I just making something like that:
![screenshot1](https://user-images.githubusercontent.com/33581850/71350369-7accdd80-2571-11ea-8331-ae744c1e0af2.png)
After that the file is not deleted and remains in its place in the column.
Maybe this is problem only in my hrev (hrev53606).
